### ISSUE TITLE
Starting in Django 1.5, calling .save() only updates the fields that have changed.

### ISSUE THREAD

**Issue by oppianmatt** [nyergler/effective-django#14]
Since when has that ever been the case?

It saves all the fields, not just the ones changed. You can specify a subset with update_fields but normally it will save all.

**Comment by rterehov** [comment]
+1

**Comment by romgar** [comment]
I proposed a documentation update for this part.

**Comment by romgar** [comment]
Wow. Fastest merge ever. :+1:

**Comment by romgar** [comment]
The website has not been updated with this MR.
